### ISSUE TITLE
Conversion of MLint_devel.Rnw vignette to R markdown

### ISSUE THREAD

**Issue by phyleria** [lgatto/MLInterfaces#4]
Hi,

I'm volunteering with [Sweave2Rmd](https://github.com/Bioconductor/sweave2rmd)
and we're trying to replace all Bioconductor Sweave vignettes R Markdown
vignettes. Would you be willing to accept a pull request with the R Markdown
version of Introduction to MLint_devel.Rnw from me as a contributor. I'll kindly ask you to
review and accept the pull request. You'll also need to bump the version
number in your DESCRIPTION file so that the build machines will recognize
that a new version is available.

Thanks for your time.

**Comment by lgatto** [comment]
Could you please use https://github.com/vjcitn/MLInterfaces which is at the moment more up to date and is managed by the main author of the package.

**Comment by phyleria** [comment]
Yeah sure, thank you very much!
